# Generated by Django 5.2.1 on 2025-05-22 15:54

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_can_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
