# Generated by Django 5.2.1 on 2025-06-10 17:01

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogpost_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True),
        ),
    ]
