# Generated by Django 5.2.1 on 2025-06-10 17:06

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_embedding_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embedding',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True),
        ),
    ]
