# Generated by Django 5.2.1 on 2025-06-11 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('blog', '0009_alter_blogpost_embedding'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Analytics',
            new_name='PageView',
        ),
    ]
