# Generated by Django 5.2.1 on 2025-06-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_rename_analytics_pageview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
